services:
  postgres: 
    image: postgres:16
    container_name: ai-chat-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5132:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      
volumes:
  postgres:
    